### ISSUE TITLE
最新Android7.1.1 Beta版本会引起crash

### ISSUE THREAD

**Issue by venshine** [liaohuqiu/android-UCToast#7]
Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- window android.view.ViewRootImpl$W@f8fe192 has already been added

**Comment by bihe0832** [comment]
是的，google也出手了~

https://android.googlesource.com/platform/frameworks/base/+/dc24f93

Prevent apps to overlay other apps via toast windows

It was possible for apps to put toast type windows
that overlay other apps which toast winodws aren't
removed after a timeout.

Now for apps targeting SDK greater than N MR1 to add a
toast window one needs to have a special token. The token
is added by the notificatoion manager service only for
the lifetime of the shown toast and is then removed
including all windows associated with this token. This
prevents apps to add arbitrary toast windows.

Since legacy apps may rely on the ability to directly
add toasts we mitigate by allowing these apps to still
add such windows for unlimited duration if this app is
the currently focused one, i.e. the user interacts with
it then it can overlay itself, otherwise we make sure
these toast windows are removed after a timeout like
a toast would be.

We don't allow more that one toast window per UID being
added at a time which prevents 1) legacy apps to put the
same toast after a timeout to go around our new policy
of hiding toasts after a while; 2) modern apps to reuse
the passed token to add more than one window; Note that
the notification manager shows toasts one at a time.

bug:30150688

Change-Id: Icc8f8dbd060762ae1a7b1720e96c5afdb8aff3fd

**Comment by wangchang163** [comment]
怎么解决吐司问题

**Comment by wangchang163** [comment]
我也遇到了这个问题，在锤子7.1.1系统上，吐司崩溃，其他手机没问题

**Comment by sheep0704** [comment]
解决：http://blog.csdn.net/DJY1992/article/details/77942568
